Parse monitoring data for the infrastructure page #21
DalgoT4D/dalgo-admin pull request #24
Opened 2024-02-17 13:29 UTC by jayesh9747

Hello @fatchat, could you please review my pull request and any related issues or modifications? If you identify any specific issues, kindly provide details so that I can promptly address and improve the code accordingly.

2024-02-18 04:12 UTC, fatchat requested changes
the problem with returning arrays is that callers may hardcode the indexes they use e.g. `array[0], array[1], array[-2]` etc. and then when you enhance the function to change the size of the array those callers will break

one solution is to main a list of array indexes, like
```
I_CPU = 0
I_RAM = 1
I_SOMETHING_ELSE = 2
```

... but i would recommend you just return a dictionary

if you do that in both `read_file` and `getLiveData` (which should be `get_live_data`) then your update in `infra_info` will be simpler

2024-02-18 04:12 UTC, fatchat commented on dalgo_admin/dalgo_admin_app/views.py
> +def Write_Monitoring_file():
keep all function names `snake_case`

2024-02-18 04:12 UTC, fatchat commented on dalgo_admin/dalgo_admin_app/views.py
> +    output_file = root_dir / "assets" / "promtail_output.txt"
this file is under source control, if you overwrite it you will end up with diffs

2024-02-18 08:11 UTC, jayesh9747 commented on dalgo_admin/dalgo_admin_app/views.py
> +    output_file = root_dir / "assets" / "promtail_output.txt"
@fatchat sure sir , i will do all modification according to you .

2024-02-18 08:18 UTC, jayesh9747 commented on dalgo_admin/dalgo_admin_app/views.py
> +    output_file = root_dir / "assets" / "promtail_output.txt"
> this file is under source control, if you overwrite it you will end up with diffs

Can I use append mode  instead of write mode to write to the file in order to avoid overwriting it and creating diffs in the version control system?

2024-02-18 15:03 UTC, fatchat commented on dalgo_admin/dalgo_admin_app/views.py
> +    output_file = root_dir / "assets" / "promtail_output.txt"
any changes will be detected by `git`...

2024-02-18 15:36 UTC, jayesh9747 commented on dalgo_admin/dalgo_admin_app/views.py
> +    output_file = root_dir / "assets" / "promtail_output.txt"
so , what is solution of this issue ?

2024-02-18 15:45 UTC, fatchat commented on dalgo_admin/dalgo_admin_app/views.py
> +    output_file = root_dir / "assets" / "promtail_output.txt"
one way is to create a folder like `downloads` or `cache` or something like that, and add it to `.gitignore`. save your downloaded promtail response to that folder. you should put a timestamp in the filename so you can easily 
1. fetch the latest
2. delete old ones

2024-02-19 05:49 UTC, jayesh9747 commented
hello @fatchat , good morning . I have made all the changes as advised. Could you please review the updated code?

2024-03-09 02:30 UTC, fatchat approved these changes

2024-03-09 02:30 UTC, merged

2024-03-14 05:09 UTC, jayesh9747 commented
fixed #21